-- =============================================================
-- 0008 — Patients, history, allergies and visits
--
-- Visit-centric by design: everything clinical hangs off a `visit`, never
-- directly off a patient. A patient who returns three times has three
-- visits, each with its own vitals, symptoms and assessment. This is what
-- makes the longitudinal risk detector possible at all, and it is how every
-- real EMR is modelled.
--
-- NO GOVERNMENT ID DATA. Patients are keyed by a system-issued 12-digit
-- RHID. See docs/DECISIONS.md D-002.
-- =============================================================

-- Trigram index support for fuzzy patient-name search. Names are entered by
-- ear in multiple scripts and transliterations, so exact match is not enough.
create extension if not exists pg_trgm;

create type public.patient_sex as enum ('female', 'male', 'other', 'undisclosed');

-- Where a fact came from matters clinically: self-reported history and
-- doctor-confirmed history must never be weighted the same by the AI.
create type public.data_source_kind as enum (
  'stated',            -- the patient said so
  'ocr',               -- extracted from an uploaded document
  'device',            -- read from an IoT device
  'assistant_observed',
  'doctor_confirmed'
);

create type public.allergy_severity as enum ('mild', 'moderate', 'severe', 'unknown');

create type public.visit_status as enum (
  'open',                      -- intake in progress
  'awaiting_assessment',
  'assessed',
  'awaiting_doctor_review',    -- LOW tier queued
  'awaiting_assistant_action', -- doctor flagged something back
  'awaiting_consultation',     -- MEDIUM tier scheduled
  'referred',                  -- HIGH tier
  'closed'
);

create type public.risk_tier as enum ('low', 'medium', 'high');

-- -------------------------------------------------------------
-- Patients
-- -------------------------------------------------------------
create table public.patients (
  id                    uuid primary key default gen_random_uuid(),

  -- Human-facing key: 12 digits, Verhoeff check digit, non-zero leading
  -- digit. Generated by utils/rhid.js. The shape is enforced here too so a
  -- malformed id cannot be written by any path.
  rhid                  text not null unique
                        check (rhid ~ '^[1-9][0-9]{11}$'),

  -- Optional. Only if the patient already has one. Never required, never a key.
  abha_id               text unique,

  full_name             text not null check (length(trim(full_name)) > 0),
  -- Rural patients frequently do not know their date of birth, so either is
  -- acceptable — but not neither, because paediatric dosing depends on age.
  date_of_birth         date,
  age_years             integer check (age_years between 0 and 130),
  sex                   public.patient_sex not null default 'undisclosed',

  preferred_language    text not null default 'hi',
  village               text,
  phone                 text,

  -- The facility that registered them. Anchors every RLS policy below.
  facility_id           uuid not null references public.facilities(id) on delete restrict,

  -- Urgent-case bypass: a record is created immediately with minimal detail
  -- so treatment is never blocked on paperwork, and flagged for completion.
  emergency_registration boolean not null default false,
  registration_complete  boolean not null default true,

  created_by            uuid references public.profiles(id) on delete restrict,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint patient_age_known check (
    date_of_birth is not null or age_years is not null
  )
);

create index patients_facility_idx on public.patients(facility_id);
create index patients_name_trgm_idx on public.patients using gin (lower(full_name) gin_trgm_ops);
create index patients_phone_idx on public.patients(phone) where phone is not null;
create index patients_incomplete_idx on public.patients(facility_id)
  where registration_complete = false;

create trigger patients_set_updated_at before update on public.patients
  for each row execute function public.set_updated_at();

-- -------------------------------------------------------------
-- History and allergies
-- -------------------------------------------------------------
create table public.patient_history (
  id          uuid primary key default gen_random_uuid(),
  patient_id  uuid not null references public.patients(id) on delete cascade,
  condition   text not null,
  since       text,                      -- free text: "2 years", "childhood"
  notes       text,
  source      public.data_source_kind not null default 'stated',
  recorded_by uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index patient_history_patient_idx on public.patient_history(patient_id);

create table public.allergies (
  id          uuid primary key default gen_random_uuid(),
  patient_id  uuid not null references public.patients(id) on delete cascade,
  substance   text not null,
  reaction    text,
  severity    public.allergy_severity not null default 'unknown',
  source      public.data_source_kind not null default 'stated',
  recorded_by uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index allergies_patient_idx on public.allergies(patient_id);
-- A UNIQUE table constraint cannot contain an expression, so the
-- case-insensitive uniqueness is a unique index instead.
create unique index allergies_patient_substance_uniq
  on public.allergies (patient_id, lower(substance));

comment on table public.allergies is
  'Feeds the hard allergy gate in the medicine rules engine. A missing '
  'allergy record must never be treated as "no allergy" — absence of data '
  'is not evidence of absence.';

-- -------------------------------------------------------------
-- Visits — the spine of the clinical model
-- -------------------------------------------------------------
create table public.visits (
  id           uuid primary key default gen_random_uuid(),
  patient_id   uuid not null references public.patients(id) on delete restrict,
  facility_id  uuid not null references public.facilities(id) on delete restrict,
  assistant_id uuid references public.profiles(id) on delete restrict,

  status       public.visit_status not null default 'open',
  -- Populated in Phase 4 by the triage engine. Never written by a client.
  final_tier   public.risk_tier,

  chief_complaint text,
  started_at   timestamptz not null default now(),
  closed_at    timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index visits_patient_idx on public.visits(patient_id, started_at desc);
create index visits_facility_status_idx on public.visits(facility_id, status);
create index visits_open_idx on public.visits(facility_id)
  where status not in ('closed');

create trigger visits_set_updated_at before update on public.visits
  for each row execute function public.set_updated_at();

-- -------------------------------------------------------------
-- Helper: is this patient/visit inside the caller's reach?
-- -------------------------------------------------------------
create or replace function public.patient_in_my_facility(target_facility uuid)
returns boolean
language sql stable
security definer
set search_path = public
as $$
  select case
    -- An assistant sees exactly their own facility.
    when public.jwt_role() = 'clinical_assistant'
      then target_facility = public.jwt_facility_id()
    -- Doctors see their district, since consultations are district-pooled.
    when public.jwt_role() in ('doctor', 'senior_doctor')
      then exists (
        select 1 from public.facilities f
        where f.id = target_facility and f.district_id = public.jwt_district_id()
      )
    else false
  end;
$$;

-- =============================================================
-- RLS
--
-- Admins are deliberately absent from every policy below. "Admin cannot
-- edit patient data" is a requirement, and admins have no clinical READ
-- either — region-level management does not require seeing a named
-- patient's record.
-- =============================================================
alter table public.patients        enable row level security;
alter table public.patient_history enable row level security;
alter table public.allergies       enable row level security;
alter table public.visits          enable row level security;

create policy patients_read on public.patients
  for select to authenticated
  using (public.patient_in_my_facility(facility_id));

create policy patients_insert on public.patients
  for insert to authenticated
  with check (
    public.jwt_role() = 'clinical_assistant'
    and facility_id = public.jwt_facility_id()
  );

create policy patients_update on public.patients
  for update to authenticated
  using (public.patient_in_my_facility(facility_id))
  with check (public.patient_in_my_facility(facility_id));

-- No delete policy anywhere: patient records are never deleted.

create policy patient_history_read on public.patient_history
  for select to authenticated
  using (exists (
    select 1 from public.patients p
    where p.id = patient_history.patient_id
      and public.patient_in_my_facility(p.facility_id)
  ));

create policy patient_history_write on public.patient_history
  for insert to authenticated
  with check (exists (
    select 1 from public.patients p
    where p.id = patient_history.patient_id
      and public.patient_in_my_facility(p.facility_id)
  ));

create policy allergies_read on public.allergies
  for select to authenticated
  using (exists (
    select 1 from public.patients p
    where p.id = allergies.patient_id
      and public.patient_in_my_facility(p.facility_id)
  ));

create policy allergies_write on public.allergies
  for insert to authenticated
  with check (exists (
    select 1 from public.patients p
    where p.id = allergies.patient_id
      and public.patient_in_my_facility(p.facility_id)
  ));

create policy visits_read on public.visits
  for select to authenticated
  using (public.patient_in_my_facility(facility_id));

create policy visits_insert on public.visits
  for insert to authenticated
  with check (
    public.jwt_role() = 'clinical_assistant'
    and facility_id = public.jwt_facility_id()
  );

create policy visits_update on public.visits
  for update to authenticated
  using (public.patient_in_my_facility(facility_id))
  with check (public.patient_in_my_facility(facility_id));

-- -------------------------------------------------------------
-- Grants: no client may delete clinical data, ever.
-- `final_tier` is written only by the triage engine via the service role.
-- -------------------------------------------------------------
revoke delete on public.patients, public.patient_history,
                 public.allergies, public.visits from authenticated;

revoke update on public.visits from authenticated;
grant  update (status, chief_complaint, closed_at) on public.visits to authenticated;

revoke update on public.patients from authenticated;
grant  update (full_name, date_of_birth, age_years, sex, preferred_language,
               village, phone, abha_id, registration_complete)
  on public.patients to authenticated;

-- -------------------------------------------------------------
-- New audit actions for this phase
-- -------------------------------------------------------------
alter type public.audit_action add value if not exists 'patient_searched';
alter type public.audit_action add value if not exists 'visit_opened';
alter type public.audit_action add value if not exists 'visit_closed';
alter type public.audit_action add value if not exists 'emergency_registration';
